### ISSUE TITLE
can you update module on https://packagist.org/

### ISSUE THREAD

**Issue by robbertstevens** [abelbm/magento2-disable-frontend#4]
@abelbm Now you cannot install it on php 7.1+

thanks

**Comment by abelbm** [comment]
@robbertstevens Hello Robbert, I didn't get the message. You "can" or "can't" install it in php 7.1+ ?

**Comment by robbertstevens** [comment]
```
[InvalidArgumentException]                                                                                             
  Package abelbm/magento2-disablefrontend at version  has a PHP requirement incompatible with your PHP version (7.1.25)
```

**Comment by abelbm** [comment]
@robbertstevens 
I don't get it.
I set in the composer.json
"require": {
        "php": "~5.5.0|~5.6.0|~7.0.0|~7.1.0|~7.2.0"
    },
what I am missing?

**Comment by robbertstevens** [comment]
@abelbm  I think you forgot to add a new tag. I cannot install via composer.

**Comment by abelbm** [comment]
yeah, I'm searching for the missing tag. 
Even for me is not working.
If you find something I'll appreciate.
thanks

**Comment by abelbm** [comment]
@robbertstevens Robbert is solved!
Let me know if is working for you so I can close this Issue.

**Comment by robbertstevens** [comment]
@abelbm I'll try to install tomorrow. But I think this will fix it! Thanks for the fast reponse!

**Comment by robbertstevens** [comment]
It works now! @abelbm
